#use rubis;
#SELECT bid FROM bids WHERE bid IS NOT NULL;;
#SELECT buyer_id FROM buy_now WHERE buyer_id IS NOT NULL; 
#SELECT name FROM categories WHERE name IS NOT NULL;
#SELECT comment FROM comments WHERE comment IS NOT NULL;
#SELECT buy_now FROM items WHERE buy_now IS NOT NULL;
#SELECT name FROM regions WHERE name IS NOT NULL;
#SELECT balance FROM users WHERE balance IS NOT NULL;

#DROP TABLE IF EXISTS BLACKHOLEbids;
#CREATE TABLE BLACKHOLEbids LIKE bids;
#ALTER TABLE BLACKHOLEbids ENGINE = BLACKHOLE;
#INSERT INTO BLACKHOLEbids SELECT * FROM bids ORDER BY id;
#DROP TABLE IF EXISTS BLACKHOLEitems;
#CREATE TABLE BLACKHOLEitems LIKE items;
#ALTER TABLE BLACKHOLEitems ENGINE = BLACKHOLE;
#INSERT INTO BLACKHOLEitems SELECT * FROM items ORDER BY id;
#DROP TABLE IF EXISTS BLACKHOLEusers;
#CREATE TABLE BLACKHOLEusers LIKE users;
#ALTER TABLE BLACKHOLEusers ENGINE = BLACKHOLE;
#INSERT INTO BLACKHOLEusers SELECT * FROM users ORDER BY id;

use rubis;
DELIMITER //
CREATE PROCEDURE preload()
BEGIN
SELECT bid FROM bids WHERE bid IS NOT NULL;
SELECT buyer_id FROM buy_now WHERE buyer_id IS NOT NULL; 
SELECT name FROM categories WHERE name IS NOT NULL;
SELECT comment FROM comments WHERE comment IS NOT NULL;
SELECT buy_now FROM items WHERE buy_now IS NOT NULL;
SELECT name FROM regions WHERE name IS NOT NULL;
SELECT balance FROM users WHERE balance IS NOT NULL;
END //
DELIMITER ;