/*
Note: datetime doesnot carry information regarding the timezone, whereas timestamp does.
Nevertheless the shadow operations mandates to apply the same values in all datacenters. 
The issue rises when Mysql timestamp fields expect user to insert a local data and automatically converts 
it to UTC for storage. 
Therefore, we keep the data fields as DATETIME and at the applicaition side we manage to insert only data
in UTC format while when retrieving data we convert to user local timestmap also at the application level. 

*/


DROP DATABASE IF EXISTS rubis;
CREATE DATABASE rubis;
connect rubis;

CREATE TABLE categories (
   id INTEGER UNSIGNED NOT NULL UNIQUE AUTO_INCREMENT, /*this table is not changed over the experiment, keep it */
   name VARCHAR(50),
   _SP_del bool default false,
   _SP_ts int default 0,
   _SP_clock varchar(100) default "0-0",
   PRIMARY KEY(id)   
);

CREATE TABLE regions (
   id INTEGER UNSIGNED NOT NULL UNIQUE AUTO_INCREMENT, /*this table is not changed over the experiment, keep it */
   name VARCHAR(25),
   _SP_del bool default false,
   _SP_ts int default 0,
   _SP_clock varchar(100) default "0-0",
   PRIMARY KEY(id)
);

CREATE TABLE users (
   id            INTEGER UNSIGNED NOT NULL UNIQUE /*AUTO_INCREMENT - txmud doesnt allow autoincrement fields*/,
   firstname     VARCHAR(20),
   lastname      VARCHAR(20),
   nickname      VARCHAR(20) NOT NULL UNIQUE,
   password      VARCHAR(20) NOT NULL,
   email         VARCHAR(50) NOT NULL,
   rating        INTEGER,
   balance       FLOAT,
   creation_date DATETIME, /*DATETIME, - doesnt carry information about timezone and may affect remote datacenters */ 
   region        INTEGER UNSIGNED NOT NULL,
   PRIMARY KEY(id),
   INDEX auth (nickname,password),
   INDEX region_id (region),
   _SP_del bool default false,
   _SP_ts int default 0,
   _SP_clock varchar(100) default "0-0"
);

CREATE TABLE items (
   id            INTEGER UNSIGNED NOT NULL UNIQUE /*AUTO_INCREMENT - txmud doesnt allow autoincrement fields*/,
   name          VARCHAR(100),
   description   VARCHAR(10000),
   initial_price FLOAT UNSIGNED NOT NULL,
   quantity      INTEGER UNSIGNED NOT NULL,
   reserve_price FLOAT UNSIGNED DEFAULT 0,
   buy_now       FLOAT UNSIGNED DEFAULT 0,
   nb_of_bids    INTEGER UNSIGNED DEFAULT 0,
   max_bid       FLOAT UNSIGNED DEFAULT 0,
   start_date    DATETIME, /*DATETIME, - doesnt carry information about timezone and may affect remote datacenters */
   end_date      DATETIME, /*DATETIME, - doesnt carry information about timezone and may affect remote datacenters */
   seller        INTEGER UNSIGNED NOT NULL,
   category      INTEGER UNSIGNED NOT NULL,
   PRIMARY KEY(id),
   INDEX seller_id (seller),
   INDEX category_id (category),
   INDEX end_date_time (end_date),
   _SP_del bool default false,
   _SP_ts int default 0,
   _SP_clock varchar(100) default "0-0"
);

CREATE TABLE bids (
   id      INTEGER UNSIGNED NOT NULL UNIQUE /*AUTO_INCREMENT - txmud doesnt allow autoincrement fields*/,
   user_id INTEGER UNSIGNED NOT NULL,
   item_id INTEGER UNSIGNED NOT NULL,
   qty     INTEGER UNSIGNED NOT NULL,
   bid     FLOAT UNSIGNED NOT NULL,
   max_bid FLOAT UNSIGNED NOT NULL,
   date    DATETIME, /*DATETIME, - doesnt carry information about timezone and may affect remote datacenters */
   PRIMARY KEY(id),
   INDEX item (item_id),
   INDEX user (user_id),
   _SP_del bool default false,
   _SP_ts int default 0,
   _SP_clock varchar(100) default "0-0"
);

CREATE TABLE comments (
   id           INTEGER UNSIGNED NOT NULL UNIQUE /*AUTO_INCREMENT - txmud doesnt allow autoincrement fields*/,
   from_user_id INTEGER UNSIGNED NOT NULL,
   to_user_id   INTEGER UNSIGNED NOT NULL,
   item_id      INTEGER UNSIGNED NOT NULL,
   rating       INTEGER,
   date         DATETIME, /*DATETIME, - doesnt carry information about timezone and may affect remote datacenters */
   comment      VARCHAR(10000),
   PRIMARY KEY(id),
   INDEX from_user (from_user_id),
   INDEX to_user (to_user_id),
   INDEX item (item_id),
   _SP_del bool default false,
   _SP_ts int default 0,
   _SP_clock varchar(100) default "0-0"
);

CREATE TABLE buy_now (
   id       INTEGER UNSIGNED NOT NULL UNIQUE /*AUTO_INCREMENT - txmud doesnt allow autoincrement fields*/,
   buyer_id INTEGER UNSIGNED NOT NULL,
   item_id  INTEGER UNSIGNED NOT NULL,
   qty      INTEGER UNSIGNED NOT NULL,
   date     DATETIME, /*DATETIME, - doesnt carry information about timezone and may affect remote datacenters */
   PRIMARY KEY(id),
   INDEX buyer (buyer_id),
   INDEX item (item_id),
   _SP_del bool default false,
   _SP_ts int default 0,
   _SP_clock varchar(100) default "0-0"
);


/*==========================================*/
# regions(name) for RUBiS database
# This file has been automatically generated by generate_regions.awk script usingas input file

INSERT INTO regions(name) VALUES ('AZ--Phoenix');
INSERT INTO regions(name) VALUES ('CA--Los Angeles');
INSERT INTO regions(name) VALUES ('CA--Oakland');
INSERT INTO regions(name) VALUES ('CA--Sacramento');
INSERT INTO regions(name) VALUES ('CA--San Diego');
INSERT INTO regions(name) VALUES ('CA--San Francisco');
INSERT INTO regions(name) VALUES ('CA--San Jose');
INSERT INTO regions(name) VALUES ('CO--Denver');
INSERT INTO regions(name) VALUES ('CT--Hartford');
INSERT INTO regions(name) VALUES ('DC--Washington');
INSERT INTO regions(name) VALUES ('FL--Jacksonville');
INSERT INTO regions(name) VALUES ('FL--Miami');
INSERT INTO regions(name) VALUES ('FL--Orlando');
INSERT INTO regions(name) VALUES ('FL--Tampa-St. Pete');
INSERT INTO regions(name) VALUES ('FL--West Palm Beach');
INSERT INTO regions(name) VALUES ('GA--Atlanta');
INSERT INTO regions(name) VALUES ('HI--Honolulu');
INSERT INTO regions(name) VALUES ('ID--Billings-Boise');
INSERT INTO regions(name) VALUES ('IL--Chicago');
INSERT INTO regions(name) VALUES ('IN--Indianapolis');
INSERT INTO regions(name) VALUES ('KS--Kansas City');
INSERT INTO regions(name) VALUES ('KY--Louisville');
INSERT INTO regions(name) VALUES ('LA--New Orleans');
INSERT INTO regions(name) VALUES ('MA--Boston ');
INSERT INTO regions(name) VALUES ('MD--Baltimore');
INSERT INTO regions(name) VALUES ('MI--Detroit');
INSERT INTO regions(name) VALUES ('MI--Grand Rapids');
INSERT INTO regions(name) VALUES ('MN--Minn-St. Paul');
INSERT INTO regions(name) VALUES ('MO--Kansas City');
INSERT INTO regions(name) VALUES ('MO--St. Louis');
INSERT INTO regions(name) VALUES ('MT--Billings-Boise');
INSERT INTO regions(name) VALUES ('NC--Charlotte');
INSERT INTO regions(name) VALUES ('NC--Greensboro');
INSERT INTO regions(name) VALUES ('NC--Raleigh-Durham');
INSERT INTO regions(name) VALUES ('ND--Bismarck-Pierre');
INSERT INTO regions(name) VALUES ('NM--Albuquerque');
INSERT INTO regions(name) VALUES ('NV--Las Vegas');
INSERT INTO regions(name) VALUES ('NY--Albany');
INSERT INTO regions(name) VALUES ('NY--Buffalo');
INSERT INTO regions(name) VALUES ('NY--New York');
INSERT INTO regions(name) VALUES ('NY--Rochester');
INSERT INTO regions(name) VALUES ('OH--Cincinnati');
INSERT INTO regions(name) VALUES ('OH--Cleveland');
INSERT INTO regions(name) VALUES ('OH--Columbus');
INSERT INTO regions(name) VALUES ('OH--Dayton');
INSERT INTO regions(name) VALUES ('OK--Oklahoma City');
INSERT INTO regions(name) VALUES ('OR--Portland');
INSERT INTO regions(name) VALUES ('PA--Philadelphia');
INSERT INTO regions(name) VALUES ('PA--Pittsburgh');
INSERT INTO regions(name) VALUES ('RI--Providence');
INSERT INTO regions(name) VALUES ('SD--Bismarck-Pierre');
INSERT INTO regions(name) VALUES ('TN--Memphis');
INSERT INTO regions(name) VALUES ('TN--Nashville');
INSERT INTO regions(name) VALUES ('TX--Austin');
INSERT INTO regions(name) VALUES ('TX--Dallas-Fort Worth');
INSERT INTO regions(name) VALUES ('TX--Houston');
INSERT INTO regions(name) VALUES ('TX--San Antonio');
INSERT INTO regions(name) VALUES ('UT--Salt Lake City');
INSERT INTO regions(name) VALUES ('VA--Norfolk-VA Beach');
INSERT INTO regions(name) VALUES ('VA--Richmond');
INSERT INTO regions(name) VALUES ('WA--Seattle-Tacoma');
INSERT INTO regions(name) VALUES ('WI--Milwaukee');


# categories(name) for RUBiS database
# This file has been automatically generated by generate_categories.awk script usingas input file

INSERT INTO categories(name) VALUES ('Antiques & Art ');
INSERT INTO categories(name) VALUES ('Books ');
INSERT INTO categories(name) VALUES ('Business, Office & Industrial ');
INSERT INTO categories(name) VALUES ('Clothing & Accessories ');
INSERT INTO categories(name) VALUES ('Coins ');
INSERT INTO categories(name) VALUES ('Collectibles ');
INSERT INTO categories(name) VALUES ('Computers ');
INSERT INTO categories(name) VALUES ('Consumer Electronics ');
INSERT INTO categories(name) VALUES ('Dolls & Bears ');
INSERT INTO categories(name) VALUES ('Home & Garden ');
INSERT INTO categories(name) VALUES ('Jewelry, Gems & Watches ');
INSERT INTO categories(name) VALUES ('Movies & Television ');
INSERT INTO categories(name) VALUES ('Music ');
INSERT INTO categories(name) VALUES ('Photo ');
INSERT INTO categories(name) VALUES ('Pottery & Glass ');
INSERT INTO categories(name) VALUES ('Sports ');
INSERT INTO categories(name) VALUES ('Stamps ');
INSERT INTO categories(name) VALUES ('Tickets & Travel ');
INSERT INTO categories(name) VALUES ('Toys & Hobbies ');
INSERT INTO categories(name) VALUES ('Everything Else ');


GRANT all on rubis.* to 'sa'@'%' identified by '101010';
GRANT all on rubis.* to 'sa'@'localhost' identified by '101010';
GRANT all on rubis.* to 'sa'@'wks-40-15.mpi-sws.org' identified by '101010';
GRANT all on rubis.* to 'sa'@'139.19.131.107' identified by '101010';
